### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nicolasblanco** [nicolasblanco/shopix#1]
I would like to update dependencies, mainly : Phoenix, Guardian, Bamboo, Ecto to latest versions.

**Comment by nicolasblanco** [comment]
Upgrading Guardian will require some work in the `GuardianSerializer` as the philosophy has changed...

**Comment by joaothallis** [comment]
Hey, you can use https://github.com/apps/dependabot for update dependencies, it creates PRs updating your libs.

Is free for open-source projects

**Comment by nicolasblanco** [comment]
@joaothallis : yes thanks, I've added it. But to update those dependencies (phoenix, ecto, guardian), some development/changes will be necessary 👍

**Comment by nicolasblanco** [comment]
I've updated the project to latest Guardian version 👍

**Comment by nicolasblanco** [comment]
Just updated from Phoenix 1.3 to Phoenix 1.4 😄

**Comment by nicolasblanco** [comment]
As I've updated the Elixir libs I wanted to update, I'm closing this one.
